Vagrant.configure("2") do |config|
  ssh_key_path = "~/.ssh/"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.229.4"
  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh"
  config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa.pub' }", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "script.sh", destination: "/home/vagrant"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  config.vm.provision "install-docker", type: "shell", path: "install_docker.sh"
  config.vm.provision "ds", type: "shell", inline: "systemctl start docker"
  config.vm.provision "jup", type: "shell", inline: <<-Shell
    docker pull jenkins
    docker run -p 8080:8080 -p 50000:50000 jenkins
  Shell
end
