Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-19.04"
  config.vm.box_version = "201906.18.0"
  config.vm.hostname = "ubuntu1904"
  config.vm.network :private_network, ip: "192.168.229.5"
  config.vm.synced_folder "test/", "/home/vagrant/hostfolder/", create: true
	config.vm.provider "virtualbox" do |vb|
    vb.name = "ub1904"
  end
  # config.ssh.username = "roman"
  # config.ssh.password = "1234"
end
