Vagrant.configure("2") do |config|
  config.vm.box = "chaifeng/ubuntu-18.04-docker-19.03"
  config.vm.box_version = "201812.27.0"
  config.vm.network :private_network, ip: "192.168.229.7"
  config.vm.provider "virtualbox" do |v|
  	v.name = "ub1804-docker1903"
	end
end
