NODE_COUNT = 3
BOX_IMAGE = "centos/7"
Vagrant.configure("2") do |config|
  ssh_key_path = "~/.ssh/"

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.network "private_network", ip: "192.168.229.1#{i-1}"
      subconfig.vm.provider "virtualbox" do |v|
        v.memory = 3072
      end
    end
  end
  config.vm.define "node10RAM" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.network "private_network", ip: "192.168.229.3"
    subconfig.vm.provider "virtualbox" do |v|
      v.memory = 8192
    end
  end

  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh"
  config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa.pub' }", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "script.sh", destination: "/home/vagrant"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  config.vm.provision "install-docker", type: "shell", path: "script.sh"
  config.vm.provision "ds", type: "shell", inline: "systemctl start docker"
end
