Vagrant.configure("2") do |config|
  config.vm.box = "ub2204-docker"
  config.vm.network :private_network, ip: "192.168.229.5"
	config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins"
  end
  config.vm.provision "prepare", type: "shell", path: "../ubuntu/prepare.sh"
  config.vm.provision "install-docker", type: "shell", path: "../ubuntu/install_docker.sh"
  config.vm.provision "install-jenkins", type: "shell", path: "../docker/run_jenkins.sh"
end
