NODE_COUNT = 3
BOX_IMAGE = "centos/7"
Vagrant.configure("2") do |config|
  ssh_key_path = "~/.ssh/"

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.network "private_network", ip: "192.168.229.1#{i-1}"
    end
  end

  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh"
  config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa' }", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa.pub' }", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  # (1..NODE_COUNT).each do |i|
  #   config.vm.define "node#{i}" do |subconfig|
  #     subconfig.vm.box = "centos/7"
  #     subconfig.vm.network "private_network", ip: "192.168.229.1#{i-1}"
  #     subconfig.vm.provider "virtualbox" do |v|
  #       v.memory = 2048
  #     end
  #     subconfig.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh"
  #     subconfig.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa' }", destination: "/home/vagrant/.ssh/id_rsa"
  #     subconfig.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa.pub' }", destination: "/home/vagrant/.ssh/id_rsa.pub"
  #     subconfig.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  #   end
  # end
end
