Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1905.1"
  config.vm.hostname = "centos7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	# config.vm.provider "virtualbox" do |v|
  	# v.name = "centos7"
  # end
end
