Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7"
  config.vm.network :private_network, ip: "192.168.229.6"
  config.vm.synced_folder "test/", "/home/vagrant/hostfolder/", create: true
	config.vm.provider "virtualbox" do |v|
  	v.name = "centos7"
	end
end
