NODE_COUNT = 3
BOX_IMAGE = "centos/7"
Vagrant.configure("2") do |config|
  ssh_key_path = "~/.ssh/"

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.network "private_network", ip: "192.168.229.#{5+i}"
      subconfig.vm.provider "virtualbox" do |v|
        v.memory = 3072
      end
    end
  end

  config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh"
  config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa.pub' }", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  config.vm.provision "shell", inline: "yum install -y java-1.8.0-openjdk-devel git vim gcc unzip net-tools nc telnet lsof"
  config.vm.provision "rm", type: "shell", inline: "rm -rf /home/vagrant/*"
  config.vm.provision "node", type: "shell", inline: <<-Shell
    curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
    yum install nodejs -y
  Shell


end
